In [2]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
p=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
p

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [5]:
p.shape

torch.Size([3, 2])

In [6]:
p[1:]

tensor([[5., 3.],
        [2., 1.]])

In [7]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])

In [8]:
batch_t=torch.randn(2,3,5,5)

In [9]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [10]:
img_t

tensor([[[-0.6416, -0.5388, -0.8175,  1.0283,  1.5027],
         [ 0.8445, -0.4983, -0.4640, -1.0826,  0.2512],
         [-0.3824,  1.5168, -0.3356, -0.3903, -0.3149],
         [ 0.6629,  0.3174,  2.1920,  0.5513, -0.0765],
         [-0.2403,  0.7669,  0.6150, -0.0144,  2.2098]],

        [[ 0.2250, -0.9952,  0.6647,  0.4193,  3.6736],
         [-0.5004, -0.0987, -1.5915,  1.7743,  1.2594],
         [-1.1429, -0.8101, -0.4361,  0.3375,  0.0375],
         [-1.1061, -3.2359, -0.1684,  0.6477,  1.8162],
         [ 1.0673,  0.2397,  0.4120,  0.2194,  1.3759]],

        [[ 0.1001, -0.9546, -0.8657,  0.2629,  0.0625],
         [-0.3002,  1.3929, -0.4890, -0.5222, -1.7532],
         [ 0.0904, -0.5459,  0.3035,  0.2439,  0.8683],
         [ 0.0264,  1.0189, -0.6799, -1.2225, -1.4919],
         [-0.4462,  0.4944,  0.9013, -0.1963,  1.0153]]])

In [11]:
img_gray_naive

tensor([[-0.1055, -0.8295, -0.3395,  0.5702,  1.7463],
        [ 0.0147,  0.2653, -0.8482,  0.0565, -0.0809],
        [-0.4783,  0.0536, -0.1560,  0.0637,  0.1970],
        [-0.1389, -0.6332,  0.4479, -0.0078,  0.0826],
        [ 0.1269,  0.5004,  0.6428,  0.0029,  1.5336]])

In [12]:
double_points=torch.ones(10,2,dtype=torch.double)


In [13]:
double_points.dtype

torch.float64

In [14]:
double_points=torch.zeros(10,2).double()

In [15]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [17]:
points_gpu=torch.tensor([[4.0,10],[5.0,3.0],[2.0,1.0]],device='cuda:1')