In [2]:
import imageio

In [3]:
img_arr=imageio.imread('../deep-learning-with-pytorch-ja-main/data/p1ch4/image-dog/bobby.jpg')

/tmp/ipykernel_140088/3249991575.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr=imageio.imread('../deep-learning-with-pytorch-ja-main/data/p1ch4/image-dog/bobby.jpg')


In [4]:
img_arr.shape

(720, 1280, 3)

In [5]:
import torch
img=torch.from_numpy(img_arr)
out=img.permute(2,0,1)

In [6]:
out.shape

torch.Size([3, 720, 1280])

In [7]:
batch_size=3
batch=torch.zeros(batch_size,3,256,256,dtype=torch.uint8)

In [9]:
import os
data_dir='../deep-learning-with-pytorch-ja-main/data/p1ch4/image-cats/'
filenames=[name for name in os.listdir(data_dir) if os.path.splitext(name)[-1]=='.png']

for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3]  # <1>
    batch[i] = img_t

/tmp/ipykernel_140088/2208575385.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [10]:
batch = batch.float()
batch/=255.0

In [12]:
import os
data_dir='../deep-learning-with-pytorch-ja-main/data/p1ch4/image-cats/'
filenames=[name for name in os.listdir(data_dir) if os.path.splitext(name)[-1]=='.png']

for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3]  # <1>
    batch[i] = img_t


n_cahnnels=batch.shape[1]
for c in range(n_cahnnels):
    mean=torch.mean(batch[:,c])
    std=torch.std(batch[:,c])
    batch[:,c]=(batch[:,c]-mean)/std

/tmp/ipykernel_140088/3230437528.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [13]:
batch

tensor([[[[ 1.5978,  1.5978,  1.5978,  ...,  1.1723,  1.1900,  1.1900],
          [ 1.5978,  1.5978,  1.5978,  ...,  1.1723,  1.1900,  1.1900],
          [ 1.5978,  1.5978,  1.5978,  ...,  1.1723,  1.1900,  1.1900],
          ...,
          [ 1.1723,  1.1545,  1.1368,  ...,  0.6936,  0.7467,  0.7999],
          [ 1.1723,  1.1545,  1.1368,  ...,  0.6758,  0.7467,  0.7822],
          [ 1.1723,  1.1545,  1.1368,  ...,  0.6758,  0.7467,  0.7822]],

         [[ 1.5253,  1.5253,  1.5253,  ...,  1.1081,  1.1460,  1.1460],
          [ 1.5253,  1.5253,  1.5253,  ...,  1.1081,  1.1460,  1.1460],
          [ 1.5253,  1.5253,  1.5253,  ...,  1.1081,  1.1460,  1.1460],
          ...,
          [ 0.2546,  0.2356,  0.2167,  ..., -0.2765, -0.2196, -0.1627],
          [ 0.2546,  0.2356,  0.2167,  ..., -0.2954, -0.2196, -0.1816],
          [ 0.2546,  0.2356,  0.2167,  ..., -0.2954, -0.2196, -0.1816]],

         [[ 0.9417,  0.9417,  0.9417,  ...,  0.6979,  0.7182,  0.7182],
          [ 0.9417,  0.9417,  

In [14]:
import imageio

In [15]:
vol_arr=imageio.volread('../deep-learning-with-pytorch-ja-main/data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083','DICOM')

Reading DICOM (examining files): 1/99 files (1.0%99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 99/99  (100.0%)


In [16]:
vol_arr.shape

(99, 512, 512)

In [17]:
vol_arr

Array([[[ -985,  -990,  -999, ..., -1017, -1008,  -971],
        [-1016,  -984,  -963, ..., -1000, -1009,  -999],
        [-1024, -1008,  -996, ...,  -979, -1021,  -987],
        ...,
        [ -920,  -942,  -944, ...,  -893,  -917,  -955],
        [ -871,  -879,  -905, ...,  -895,  -869,  -867],
        [ -876,  -855,  -873, ...,  -933,  -982,  -936]],

       [[ -982,  -989, -1020, ...,  -988,  -977,  -980],
        [-1015,  -969,  -980, ...,  -981,  -974, -1016],
        [-1020,  -978,  -972, ...,  -988,  -993, -1015],
        ...,
        [ -880,  -854,  -924, ...,  -909,  -829,  -829],
        [ -907,  -868,  -928, ...,  -909,  -901,  -894],
        [ -885,  -850,  -899, ...,  -977,  -964,  -991]],

       [[-1022, -1011,  -983, ..., -1013,  -980,  -967],
        [-1022, -1005, -1012, ...,  -948,  -966, -1008],
        [ -991,  -965,  -993, ...,  -964, -1011,  -996],
        ...,
        [ -858,  -899,  -950, ...,  -939,  -868,  -827],
        [ -948,  -914,  -918, ...,  -968,  -9

In [18]:
import csv
import numpy as np
wine_path="../deep-learning-with-pytorch-ja-main/data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy=np.loadtxt(wine_path,dtype=np.float32,delimiter=";",skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [20]:
col_list=next(csv.reader(open(wine_path),delimiter=';'))

In [21]:
wineq_numpy,col_list

(array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
        [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
        [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
        ...,
        [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
        [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
        [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [22]:
wineq=torch.from_numpy(wineq_numpy)

In [23]:
target=wineq[:,-1].long()

In [24]:
target_onehot=torch.zeros(target.shape[0],10)

In [25]:
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [26]:
target_onehot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])